
spring:
  profiles: default
server:
  port: 9091
spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
---
spring:
  profiles: instance
server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
