
spring:
  profiles: default
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    trace:
      enabled: true

config:
  name: huanyuTest
  
server:
  port: 9091
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
spring:
  profiles: instance
server:
  port: 9092
