
spring:
  profiles: default
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    trace:
      enabled: true

server:
  port: 9091
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
spring:
  profiles: instance
server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
